/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WalletTransferPostRequestDestinationsInner
import org.openapitools.client.models.WalletTransferPostRequestMessagesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param destinations 
 * @param paymentId 
 * @param mixin 
 * @param unlockTime 
 * @param messages 
 * @param ttl 
 */


data class WalletTransferPostRequest (

    @Json(name = "destinations")
    val destinations: kotlin.collections.List<WalletTransferPostRequestDestinationsInner>? = null,

    @Json(name = "payment_id")
    val paymentId: kotlin.String? = null,

    @Json(name = "mixin")
    val mixin: kotlin.Int? = null,

    @Json(name = "unlock_time")
    val unlockTime: kotlin.Int? = null,

    @Json(name = "messages")
    val messages: kotlin.collections.List<WalletTransferPostRequestMessagesInner>? = null,

    @Json(name = "ttl")
    val ttl: kotlin.Int? = null

) {


}

