/*
Elderfire API Gateway

REST API over Fuego Wallet RPC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WalletTransferPostRequestMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletTransferPostRequestMessagesInner{}

// WalletTransferPostRequestMessagesInner struct for WalletTransferPostRequestMessagesInner
type WalletTransferPostRequestMessagesInner struct {
	Address *string `json:"address,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewWalletTransferPostRequestMessagesInner instantiates a new WalletTransferPostRequestMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletTransferPostRequestMessagesInner() *WalletTransferPostRequestMessagesInner {
	this := WalletTransferPostRequestMessagesInner{}
	return &this
}

// NewWalletTransferPostRequestMessagesInnerWithDefaults instantiates a new WalletTransferPostRequestMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletTransferPostRequestMessagesInnerWithDefaults() *WalletTransferPostRequestMessagesInner {
	this := WalletTransferPostRequestMessagesInner{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *WalletTransferPostRequestMessagesInner) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletTransferPostRequestMessagesInner) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *WalletTransferPostRequestMessagesInner) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *WalletTransferPostRequestMessagesInner) SetAddress(v string) {
	o.Address = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WalletTransferPostRequestMessagesInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletTransferPostRequestMessagesInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WalletTransferPostRequestMessagesInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WalletTransferPostRequestMessagesInner) SetMessage(v string) {
	o.Message = &v
}

func (o WalletTransferPostRequestMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletTransferPostRequestMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableWalletTransferPostRequestMessagesInner struct {
	value *WalletTransferPostRequestMessagesInner
	isSet bool
}

func (v NullableWalletTransferPostRequestMessagesInner) Get() *WalletTransferPostRequestMessagesInner {
	return v.value
}

func (v *NullableWalletTransferPostRequestMessagesInner) Set(val *WalletTransferPostRequestMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletTransferPostRequestMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletTransferPostRequestMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletTransferPostRequestMessagesInner(val *WalletTransferPostRequestMessagesInner) *NullableWalletTransferPostRequestMessagesInner {
	return &NullableWalletTransferPostRequestMessagesInner{value: val, isSet: true}
}

func (v NullableWalletTransferPostRequestMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletTransferPostRequestMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


