/*
Elderfire API Gateway

REST API over Fuego Wallet RPC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WalletTransferPostRequestDestinationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletTransferPostRequestDestinationsInner{}

// WalletTransferPostRequestDestinationsInner struct for WalletTransferPostRequestDestinationsInner
type WalletTransferPostRequestDestinationsInner struct {
	Address *string `json:"address,omitempty"`
	Amount *int32 `json:"amount,omitempty"`
}

// NewWalletTransferPostRequestDestinationsInner instantiates a new WalletTransferPostRequestDestinationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletTransferPostRequestDestinationsInner() *WalletTransferPostRequestDestinationsInner {
	this := WalletTransferPostRequestDestinationsInner{}
	return &this
}

// NewWalletTransferPostRequestDestinationsInnerWithDefaults instantiates a new WalletTransferPostRequestDestinationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletTransferPostRequestDestinationsInnerWithDefaults() *WalletTransferPostRequestDestinationsInner {
	this := WalletTransferPostRequestDestinationsInner{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *WalletTransferPostRequestDestinationsInner) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletTransferPostRequestDestinationsInner) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *WalletTransferPostRequestDestinationsInner) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *WalletTransferPostRequestDestinationsInner) SetAddress(v string) {
	o.Address = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WalletTransferPostRequestDestinationsInner) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletTransferPostRequestDestinationsInner) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WalletTransferPostRequestDestinationsInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *WalletTransferPostRequestDestinationsInner) SetAmount(v int32) {
	o.Amount = &v
}

func (o WalletTransferPostRequestDestinationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletTransferPostRequestDestinationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableWalletTransferPostRequestDestinationsInner struct {
	value *WalletTransferPostRequestDestinationsInner
	isSet bool
}

func (v NullableWalletTransferPostRequestDestinationsInner) Get() *WalletTransferPostRequestDestinationsInner {
	return v.value
}

func (v *NullableWalletTransferPostRequestDestinationsInner) Set(val *WalletTransferPostRequestDestinationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletTransferPostRequestDestinationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletTransferPostRequestDestinationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletTransferPostRequestDestinationsInner(val *WalletTransferPostRequestDestinationsInner) *NullableWalletTransferPostRequestDestinationsInner {
	return &NullableWalletTransferPostRequestDestinationsInner{value: val, isSet: true}
}

func (v NullableWalletTransferPostRequestDestinationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletTransferPostRequestDestinationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


