=begin
#Elderfire API Gateway

#REST API over Fuego Wallet RPC

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::WalletTransferPostRequestMessagesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::WalletTransferPostRequestMessagesInner do
  let(:instance) { OpenapiClient::WalletTransferPostRequestMessagesInner.new }

  describe 'test an instance of WalletTransferPostRequestMessagesInner' do
    it 'should create an instance of WalletTransferPostRequestMessagesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::WalletTransferPostRequestMessagesInner)
    end
  end

  describe 'test attribute "address"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
