/*
 * Elderfire API Gateway
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalletTransferPostRequestMessagesInner
 */
public class WalletTransferPostRequestMessagesInnerTest {
    private final WalletTransferPostRequestMessagesInner model = new WalletTransferPostRequestMessagesInner();

    /**
     * Model tests for WalletTransferPostRequestMessagesInner
     */
    @Test
    public void testWalletTransferPostRequestMessagesInner() {
        // TODO: test WalletTransferPostRequestMessagesInner
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
