/*
 * Elderfire API Gateway
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WalletTransferPostRequestDestinationsInner;
import org.openapitools.client.model.WalletTransferPostRequestMessagesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalletTransferPostRequest
 */
public class WalletTransferPostRequestTest {
    private final WalletTransferPostRequest model = new WalletTransferPostRequest();

    /**
     * Model tests for WalletTransferPostRequest
     */
    @Test
    public void testWalletTransferPostRequest() {
        // TODO: test WalletTransferPostRequest
    }

    /**
     * Test the property 'destinations'
     */
    @Test
    public void destinationsTest() {
        // TODO: test destinations
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    public void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'mixin'
     */
    @Test
    public void mixinTest() {
        // TODO: test mixin
    }

    /**
     * Test the property 'unlockTime'
     */
    @Test
    public void unlockTimeTest() {
        // TODO: test unlockTime
    }

    /**
     * Test the property 'messages'
     */
    @Test
    public void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'ttl'
     */
    @Test
    public void ttlTest() {
        // TODO: test ttl
    }

}
