=begin
#Elderfire API Gateway

#REST API over Fuego Wallet RPC

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for health_get
  # Well check
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'health_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for node_block_header_by_height_height_get
  # Get block header by height (json_rpc getblockheaderbyheight)
  # @param height 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'node_block_header_by_height_height_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for node_blockcount_get
  # Get block count (json_rpc getblockcount)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'node_blockcount_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for node_height_get
  # Get node height (maps to /getheight)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'node_height_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for node_info_get
  # Get node info (maps to /getinfo)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'node_info_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for node_last_block_header_get
  # Get last block header (json_rpc getlastblockheader)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'node_last_block_header_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_balance_get
  # Get wallet balance (wallet getbalance)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'wallet_balance_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_height_get
  # Get wallet height (wallet get_height)
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'wallet_height_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_optimize_post
  # Optimize wallet (wallet optimize)
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'wallet_optimize_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_transfer_post
  # Send transfer (wallet transfer)
  # @param wallet_transfer_post_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'wallet_transfer_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_transfers_post
  # Get transfers (wallet get_transfers)
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body 
  # @return [nil]
  describe 'wallet_transfers_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
