//
// WalletTransferPostRequestMessagesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletTransferPostRequestMessagesInner: Codable, JSONEncodable, Hashable {

    public var address: String?
    public var message: String?

    public init(address: String? = nil, message: String? = nil) {
        self.address = address
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

