//
// WalletTransferPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletTransferPostRequest: Codable, JSONEncodable, Hashable {

    public var destinations: [WalletTransferPostRequestDestinationsInner]?
    public var paymentId: String?
    public var mixin: Int?
    public var unlockTime: Int?
    public var messages: [WalletTransferPostRequestMessagesInner]?
    public var ttl: Int?

    public init(destinations: [WalletTransferPostRequestDestinationsInner]? = nil, paymentId: String? = nil, mixin: Int? = nil, unlockTime: Int? = nil, messages: [WalletTransferPostRequestMessagesInner]? = nil, ttl: Int? = nil) {
        self.destinations = destinations
        self.paymentId = paymentId
        self.mixin = mixin
        self.unlockTime = unlockTime
        self.messages = messages
        self.ttl = ttl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destinations
        case paymentId = "payment_id"
        case mixin
        case unlockTime = "unlock_time"
        case messages
        case ttl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(destinations, forKey: .destinations)
        try container.encodeIfPresent(paymentId, forKey: .paymentId)
        try container.encodeIfPresent(mixin, forKey: .mixin)
        try container.encodeIfPresent(unlockTime, forKey: .unlockTime)
        try container.encodeIfPresent(messages, forKey: .messages)
        try container.encodeIfPresent(ttl, forKey: .ttl)
    }
}

