/*
 * Elderfire API Gateway
 *
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletTransferPostRequestDestinationsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletTransferPostRequestDestinationsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletTransferPostRequestDestinationsInner
        //private WalletTransferPostRequestDestinationsInner instance;

        public WalletTransferPostRequestDestinationsInnerTests()
        {
            // TODO uncomment below to create an instance of WalletTransferPostRequestDestinationsInner
            //instance = new WalletTransferPostRequestDestinationsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletTransferPostRequestDestinationsInner
        /// </summary>
        [Fact]
        public void WalletTransferPostRequestDestinationsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletTransferPostRequestDestinationsInner
            //Assert.IsType<WalletTransferPostRequestDestinationsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
