/*
 * Elderfire API Gateway
 *
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletTransferPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletTransferPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletTransferPostRequest
        //private WalletTransferPostRequest instance;

        public WalletTransferPostRequestTests()
        {
            // TODO uncomment below to create an instance of WalletTransferPostRequest
            //instance = new WalletTransferPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletTransferPostRequest
        /// </summary>
        [Fact]
        public void WalletTransferPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletTransferPostRequest
            //Assert.IsType<WalletTransferPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Destinations'
        /// </summary>
        [Fact]
        public void DestinationsTest()
        {
            // TODO unit test for the property 'Destinations'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'Mixin'
        /// </summary>
        [Fact]
        public void MixinTest()
        {
            // TODO unit test for the property 'Mixin'
        }

        /// <summary>
        /// Test the property 'UnlockTime'
        /// </summary>
        [Fact]
        public void UnlockTimeTest()
        {
            // TODO unit test for the property 'UnlockTime'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }
    }
}
