/*
 * Elderfire API Gateway
 *
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletTransferPostRequestMessagesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletTransferPostRequestMessagesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletTransferPostRequestMessagesInner
        //private WalletTransferPostRequestMessagesInner instance;

        public WalletTransferPostRequestMessagesInnerTests()
        {
            // TODO uncomment below to create an instance of WalletTransferPostRequestMessagesInner
            //instance = new WalletTransferPostRequestMessagesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletTransferPostRequestMessagesInner
        /// </summary>
        [Fact]
        public void WalletTransferPostRequestMessagesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletTransferPostRequestMessagesInner
            //Assert.IsType<WalletTransferPostRequestMessagesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
