/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WalletTransferPostRequest
import org.openapitools.client.models.WalletTransferPostRequestDestinationsInner
import org.openapitools.client.models.WalletTransferPostRequestMessagesInner

class WalletTransferPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WalletTransferPostRequest
        //val modelInstance = WalletTransferPostRequest()

        // to test the property `destinations`
        should("test destinations") {
            // uncomment below to test the property
            //modelInstance.destinations shouldBe ("TODO")
        }

        // to test the property `paymentId`
        should("test paymentId") {
            // uncomment below to test the property
            //modelInstance.paymentId shouldBe ("TODO")
        }

        // to test the property `mixin`
        should("test mixin") {
            // uncomment below to test the property
            //modelInstance.mixin shouldBe ("TODO")
        }

        // to test the property `unlockTime`
        should("test unlockTime") {
            // uncomment below to test the property
            //modelInstance.unlockTime shouldBe ("TODO")
        }

        // to test the property `messages`
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

        // to test the property `ttl`
        should("test ttl") {
            // uncomment below to test the property
            //modelInstance.ttl shouldBe ("TODO")
        }

    }
}
