// <auto-generated>
/*
 * Elderfire API Gateway
 *
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WalletTransferPostRequestMessagesInner
    /// </summary>
    public partial class WalletTransferPostRequestMessagesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransferPostRequestMessagesInner" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public WalletTransferPostRequestMessagesInner(Option<string?> address = default, Option<string?> message = default)
        {
            AddressOption = address;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string? Address { get { return this.AddressOption; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletTransferPostRequestMessagesInner {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletTransferPostRequestMessagesInner" />
    /// </summary>
    public class WalletTransferPostRequestMessagesInnerJsonConverter : JsonConverter<WalletTransferPostRequestMessagesInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="WalletTransferPostRequestMessagesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletTransferPostRequestMessagesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class WalletTransferPostRequestMessagesInner.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class WalletTransferPostRequestMessagesInner.");

            return new WalletTransferPostRequestMessagesInner(address, message);
        }

        /// <summary>
        /// Serializes a <see cref="WalletTransferPostRequestMessagesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransferPostRequestMessagesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletTransferPostRequestMessagesInner walletTransferPostRequestMessagesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletTransferPostRequestMessagesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletTransferPostRequestMessagesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransferPostRequestMessagesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletTransferPostRequestMessagesInner walletTransferPostRequestMessagesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletTransferPostRequestMessagesInner.AddressOption.IsSet && walletTransferPostRequestMessagesInner.Address == null)
                throw new ArgumentNullException(nameof(walletTransferPostRequestMessagesInner.Address), "Property is required for class WalletTransferPostRequestMessagesInner.");

            if (walletTransferPostRequestMessagesInner.MessageOption.IsSet && walletTransferPostRequestMessagesInner.Message == null)
                throw new ArgumentNullException(nameof(walletTransferPostRequestMessagesInner.Message), "Property is required for class WalletTransferPostRequestMessagesInner.");

            if (walletTransferPostRequestMessagesInner.AddressOption.IsSet)
                writer.WriteString("address", walletTransferPostRequestMessagesInner.Address);

            if (walletTransferPostRequestMessagesInner.MessageOption.IsSet)
                writer.WriteString("message", walletTransferPostRequestMessagesInner.Message);
        }
    }
}
