// <auto-generated>
/*
 * Elderfire API Gateway
 *
 * REST API over Fuego Wallet RPC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WalletTransferPostRequestDestinationsInner
    /// </summary>
    public partial class WalletTransferPostRequestDestinationsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletTransferPostRequestDestinationsInner" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="amount">amount</param>
        [JsonConstructor]
        public WalletTransferPostRequestDestinationsInner(Option<string?> address = default, Option<int?> amount = default)
        {
            AddressOption = address;
            AmountOption = amount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string? Address { get { return this.AddressOption; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public int? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletTransferPostRequestDestinationsInner {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletTransferPostRequestDestinationsInner" />
    /// </summary>
    public class WalletTransferPostRequestDestinationsInnerJsonConverter : JsonConverter<WalletTransferPostRequestDestinationsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="WalletTransferPostRequestDestinationsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletTransferPostRequestDestinationsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<int?> amount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class WalletTransferPostRequestDestinationsInner.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class WalletTransferPostRequestDestinationsInner.");

            return new WalletTransferPostRequestDestinationsInner(address, amount);
        }

        /// <summary>
        /// Serializes a <see cref="WalletTransferPostRequestDestinationsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransferPostRequestDestinationsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletTransferPostRequestDestinationsInner walletTransferPostRequestDestinationsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletTransferPostRequestDestinationsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletTransferPostRequestDestinationsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletTransferPostRequestDestinationsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletTransferPostRequestDestinationsInner walletTransferPostRequestDestinationsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletTransferPostRequestDestinationsInner.AddressOption.IsSet && walletTransferPostRequestDestinationsInner.Address == null)
                throw new ArgumentNullException(nameof(walletTransferPostRequestDestinationsInner.Address), "Property is required for class WalletTransferPostRequestDestinationsInner.");

            if (walletTransferPostRequestDestinationsInner.AddressOption.IsSet)
                writer.WriteString("address", walletTransferPostRequestDestinationsInner.Address);

            if (walletTransferPostRequestDestinationsInner.AmountOption.IsSet)
                writer.WriteNumber("amount", walletTransferPostRequestDestinationsInner.AmountOption.Value!.Value);
        }
    }
}
