/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.WalletTransferPostRequest

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test healthGet
        should("test healthGet") {
            // uncomment below to test healthGet
            //apiInstance.healthGet()
        }

        // to test nodeBlockHeaderByHeightHeightGet
        should("test nodeBlockHeaderByHeightHeightGet") {
            // uncomment below to test nodeBlockHeaderByHeightHeightGet
            //val height : kotlin.Int = 56 // kotlin.Int | 
            //apiInstance.nodeBlockHeaderByHeightHeightGet(height)
        }

        // to test nodeBlockcountGet
        should("test nodeBlockcountGet") {
            // uncomment below to test nodeBlockcountGet
            //apiInstance.nodeBlockcountGet()
        }

        // to test nodeHeightGet
        should("test nodeHeightGet") {
            // uncomment below to test nodeHeightGet
            //apiInstance.nodeHeightGet()
        }

        // to test nodeInfoGet
        should("test nodeInfoGet") {
            // uncomment below to test nodeInfoGet
            //apiInstance.nodeInfoGet()
        }

        // to test nodeLastBlockHeaderGet
        should("test nodeLastBlockHeaderGet") {
            // uncomment below to test nodeLastBlockHeaderGet
            //apiInstance.nodeLastBlockHeaderGet()
        }

        // to test walletBalanceGet
        should("test walletBalanceGet") {
            // uncomment below to test walletBalanceGet
            //apiInstance.walletBalanceGet()
        }

        // to test walletHeightGet
        should("test walletHeightGet") {
            // uncomment below to test walletHeightGet
            //apiInstance.walletHeightGet()
        }

        // to test walletOptimizePost
        should("test walletOptimizePost") {
            // uncomment below to test walletOptimizePost
            //val body : kotlin.Any = Object // kotlin.Any | 
            //apiInstance.walletOptimizePost(body)
        }

        // to test walletTransferPost
        should("test walletTransferPost") {
            // uncomment below to test walletTransferPost
            //val walletTransferPostRequest : WalletTransferPostRequest =  // WalletTransferPostRequest | 
            //apiInstance.walletTransferPost(walletTransferPostRequest)
        }

        // to test walletTransfersPost
        should("test walletTransfersPost") {
            // uncomment below to test walletTransfersPost
            //val body : kotlin.Any = Object // kotlin.Any | 
            //apiInstance.walletTransfersPost(body)
        }

    }
}
